services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: cracking_db
      POSTGRES_USER: master_user
      POSTGRES_PASSWORD: master_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - cracking-net

  master-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: master-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cracking_db
      SPRING_DATASOURCE_USERNAME: master_user
      SPRING_DATASOURCE_PASSWORD: master_pass
      JAVA_OPTS: "-Xms256m -Xmx512m"
    depends_on:
      - postgres
    restart: always
    networks:
      - cracking-net

volumes:
  postgres_data:

networks:
  cracking-net:
    external: true
